/**
 * Task Model - Task Classic Widget
 *
 * This represents a task entity in the Classic NgRx implementation.
 * All properties are immutable - updates create new objects.
 */

export enum TaskStatus {
  TODO = 'TODO',
  IN_PROGRESS = 'IN_PROGRESS',
  DONE = 'DONE'
}

export enum TaskPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH'
}

export interface Task {
  id: string;
  title: string;
  description: string | null; // Optional - not all tasks have descriptions
  status: TaskStatus;
  priority: TaskPriority;
  createdAt: string; // ISO 8601 string for easier serialization
  updatedAt: string;
  assignedTo?: string | null;
}

/**
 * Input for creating a new task (no id, timestamps generated by backend)
 */
export interface CreateTaskInput {
  title: string;
  description: string;
  status?: TaskStatus;
  priority?: TaskPriority;
  assignedTo?: string;
}

/**
 * Input for updating an existing task (all fields optional except id)
 */
export interface UpdateTaskInput {
  id: string;
  title?: string;
  description?: string;
  status?: TaskStatus;
  priority?: TaskPriority;
  assignedTo?: string;
}
