/**
 * Task Model - Task Classic Widget
 *
 * This represents a task entity in the Classic NgRx implementation.
 * All properties are immutable - updates create new objects.
 */

export enum TaskStatus {
  TODO = 'TODO',
  IN_PROGRESS = 'IN_PROGRESS',
  DONE = 'DONE'
}

export enum TaskPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH'
}

/**
 * Storage layer - Core task data
 */
export interface TaskData {
  id: string;
  title: string;
  description?: string; // Optional - not all tasks have descriptions
  status: TaskStatus;
  priority: TaskPriority;
  createdAt: string; // ISO 8601 string for easier serialization
  updatedAt: string;
}

/**
 * API layer - Task with potential relationships
 * Currently same as TaskData, but can be extended with relationships later
 * (e.g., assignedUser, comments, etc.)
 */
export interface Task extends TaskData {
  assignedTo?: string; // User ID - optional since not all tasks are assigned
  // Future: add more relationships when needed
  // comments?: Comment[];
}

/**
 * Input for creating a new task (no id, timestamps generated by backend)
 */
export interface CreateTaskInput {
  title: string;
  description: string;
  status?: TaskStatus;
  priority?: TaskPriority;
}

/**
 * Input for updating an existing task (all fields optional except id)
 */
export interface UpdateTaskInput {
  id: string;
  title?: string;
  description?: string;
  status?: TaskStatus;
  priority?: TaskPriority;
}
